"""empty message

Revision ID: 15954eb65bbc
Revises: 062a656ad412
Create Date: 2026-09-15 15:18:59.674540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15954eb65bbc'
down_revision: Union[str, None] = '062a656ad412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('dm_ne2025', sa.REAL(), nullable=True))
    op.drop_column('event', 'dm_ne2001')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('dm_ne2001', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('event', 'dm_ne2025')
    # ### end Alembic commands ###
